export const FILE_LIST_QUERY_MAX_LENGTH = 256;
export const FILE_LIST_LIMIT_MAX = 10_000;
export const FILE_LIST_EXCLUDE_NAME_MAX_LENGTH = 255;
export const FILE_LIST_EXCLUDE_NAMES_MAX = 100;
export const BRANCH_LIST_QUERY_MAX_LENGTH = 256;
export const BRANCH_LIST_LIMIT_MAX = 1_000;
